# -*- coding: utf-8 -*-
"""Bandlet VAE Smoke.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19B_QLXj0vGeodupqAEx27ODNKDb_vu01
"""

# Commented out IPython magic to ensure Python compatibility.
!rm -rf /content/Bandlet-Variational-Autoencoder
!git clone https://github.com/AngshulMajumdar/Bandlet-Variational-Autoencoder.git
# %cd /content/Bandlet-Variational-Autoencoder
!python -m pip install -q -e .

!pytest -q

import torch
from bandlet_tf import BandletTransform, BandletConfig
from bandlet_vae import BandletVAE, BandletVAEConfig

device = "cuda" if torch.cuda.is_available() else "cpu"
print("device =", device)

bt = BandletTransform(BandletConfig(auto_normalize_uint8=False, device=device))
x = torch.randn(2, 1, 64, 64, device=device)

coeffs = bt.encode(x)
x_rec = bt.reconstruct(coeffs)

print("bandlet max err =", (x - x_rec).abs().max().item())
print("bandlet mean err =", (x - x_rec).abs().mean().item())

cfg = BandletVAEConfig(
    image_size=64,
    in_channels=1,
    latent_dim=128,
    encoder_hidden_dims=(256, 128),
    decoder_hidden_dims=(128, 256),
    beta=1e-3,
    coeff_recon_weight=1.0,
    bandlet=BandletConfig(
        levels=2,
        block_size=8,
        auto_normalize_uint8=False,
        device=device,
    ),
    output_activation="identity",
)

model = BandletVAE(cfg).to(device)
x = torch.randn(4, 1, 64, 64, device=device)
out = model(x)

print(type(out))
print(out.x_hat.shape)
print(out.mu.shape)
print(out.logvar.shape)
print(out.z.shape)

losses = model.loss_function(x, out)
for k, v in losses.items():
    print(k, float(v.detach().cpu()) if torch.is_tensor(v) else v)